// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SystemMetadataColumns holds the columns for the "system_metadata" table.
	SystemMetadataColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SystemMetadataTable holds the schema information for the "system_metadata" table.
	SystemMetadataTable = &schema.Table{
		Name:       "system_metadata",
		Columns:    SystemMetadataColumns,
		PrimaryKey: []*schema.Column{SystemMetadataColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SystemMetadataTable,
	}
)

func init() {
}
