// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/vandordev/vkit-tango/internal/platform/db/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/vandordev/vkit-tango/internal/platform/db/systemmetadata"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// SystemMetadata is the client for interacting with the SystemMetadata builders.
	SystemMetadata *SystemMetadataClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.SystemMetadata = NewSystemMetadataClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("db: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("db: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		SystemMetadata: NewSystemMetadataClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		SystemMetadata: NewSystemMetadataClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		SystemMetadata.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.SystemMetadata.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.SystemMetadata.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *SystemMetadataMutation:
		return c.SystemMetadata.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("db: unknown mutation type %T", m)
	}
}

// SystemMetadataClient is a client for the SystemMetadata schema.
type SystemMetadataClient struct {
	config
}

// NewSystemMetadataClient returns a client for the SystemMetadata from the given config.
func NewSystemMetadataClient(c config) *SystemMetadataClient {
	return &SystemMetadataClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `systemmetadata.Hooks(f(g(h())))`.
func (c *SystemMetadataClient) Use(hooks ...Hook) {
	c.hooks.SystemMetadata = append(c.hooks.SystemMetadata, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `systemmetadata.Intercept(f(g(h())))`.
func (c *SystemMetadataClient) Intercept(interceptors ...Interceptor) {
	c.inters.SystemMetadata = append(c.inters.SystemMetadata, interceptors...)
}

// Create returns a builder for creating a SystemMetadata entity.
func (c *SystemMetadataClient) Create() *SystemMetadataCreate {
	mutation := newSystemMetadataMutation(c.config, OpCreate)
	return &SystemMetadataCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SystemMetadata entities.
func (c *SystemMetadataClient) CreateBulk(builders ...*SystemMetadataCreate) *SystemMetadataCreateBulk {
	return &SystemMetadataCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SystemMetadataClient) MapCreateBulk(slice any, setFunc func(*SystemMetadataCreate, int)) *SystemMetadataCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SystemMetadataCreateBulk{err: fmt.Errorf("calling to SystemMetadataClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SystemMetadataCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SystemMetadataCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SystemMetadata.
func (c *SystemMetadataClient) Update() *SystemMetadataUpdate {
	mutation := newSystemMetadataMutation(c.config, OpUpdate)
	return &SystemMetadataUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SystemMetadataClient) UpdateOne(_m *SystemMetadata) *SystemMetadataUpdateOne {
	mutation := newSystemMetadataMutation(c.config, OpUpdateOne, withSystemMetadata(_m))
	return &SystemMetadataUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SystemMetadataClient) UpdateOneID(id uuid.UUID) *SystemMetadataUpdateOne {
	mutation := newSystemMetadataMutation(c.config, OpUpdateOne, withSystemMetadataID(id))
	return &SystemMetadataUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SystemMetadata.
func (c *SystemMetadataClient) Delete() *SystemMetadataDelete {
	mutation := newSystemMetadataMutation(c.config, OpDelete)
	return &SystemMetadataDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SystemMetadataClient) DeleteOne(_m *SystemMetadata) *SystemMetadataDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SystemMetadataClient) DeleteOneID(id uuid.UUID) *SystemMetadataDeleteOne {
	builder := c.Delete().Where(systemmetadata.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SystemMetadataDeleteOne{builder}
}

// Query returns a query builder for SystemMetadata.
func (c *SystemMetadataClient) Query() *SystemMetadataQuery {
	return &SystemMetadataQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSystemMetadata},
		inters: c.Interceptors(),
	}
}

// Get returns a SystemMetadata entity by its id.
func (c *SystemMetadataClient) Get(ctx context.Context, id uuid.UUID) (*SystemMetadata, error) {
	return c.Query().Where(systemmetadata.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SystemMetadataClient) GetX(ctx context.Context, id uuid.UUID) *SystemMetadata {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SystemMetadataClient) Hooks() []Hook {
	return c.hooks.SystemMetadata
}

// Interceptors returns the client interceptors.
func (c *SystemMetadataClient) Interceptors() []Interceptor {
	return c.inters.SystemMetadata
}

func (c *SystemMetadataClient) mutate(ctx context.Context, m *SystemMetadataMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SystemMetadataCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SystemMetadataUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SystemMetadataUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SystemMetadataDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("db: unknown SystemMetadata mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		SystemMetadata []ent.Hook
	}
	inters struct {
		SystemMetadata []ent.Interceptor
	}
)
