// Code generated by ent, DO NOT EDIT.

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/vandordev/vkit-fast/database/schema"
	"github.com/vandordev/vkit-fast/internal/platform/db/systemmetadata"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	systemmetadataFields := schema.SystemMetadata{}.Fields()
	_ = systemmetadataFields
	// systemmetadataDescKey is the schema descriptor for key field.
	systemmetadataDescKey := systemmetadataFields[1].Descriptor()
	// systemmetadata.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	systemmetadata.KeyValidator = systemmetadataDescKey.Validators[0].(func(string) error)
	// systemmetadataDescCreatedAt is the schema descriptor for created_at field.
	systemmetadataDescCreatedAt := systemmetadataFields[3].Descriptor()
	// systemmetadata.DefaultCreatedAt holds the default value on creation for the created_at field.
	systemmetadata.DefaultCreatedAt = systemmetadataDescCreatedAt.Default.(func() time.Time)
	// systemmetadataDescUpdatedAt is the schema descriptor for updated_at field.
	systemmetadataDescUpdatedAt := systemmetadataFields[4].Descriptor()
	// systemmetadata.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	systemmetadata.DefaultUpdatedAt = systemmetadataDescUpdatedAt.Default.(func() time.Time)
	// systemmetadata.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	systemmetadata.UpdateDefaultUpdatedAt = systemmetadataDescUpdatedAt.UpdateDefault.(func() time.Time)
	// systemmetadataDescID is the schema descriptor for id field.
	systemmetadataDescID := systemmetadataFields[0].Descriptor()
	// systemmetadata.DefaultID holds the default value on creation for the id field.
	systemmetadata.DefaultID = systemmetadataDescID.Default.(func() uuid.UUID)
}
