// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/vandordev/vkit-tango/internal/platform/db/predicate"
	"github.com/vandordev/vkit-tango/internal/platform/db/systemmetadata"
)

// SystemMetadataDelete is the builder for deleting a SystemMetadata entity.
type SystemMetadataDelete struct {
	config
	hooks    []Hook
	mutation *SystemMetadataMutation
}

// Where appends a list predicates to the SystemMetadataDelete builder.
func (_d *SystemMetadataDelete) Where(ps ...predicate.SystemMetadata) *SystemMetadataDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SystemMetadataDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SystemMetadataDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SystemMetadataDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(systemmetadata.Table, sqlgraph.NewFieldSpec(systemmetadata.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SystemMetadataDeleteOne is the builder for deleting a single SystemMetadata entity.
type SystemMetadataDeleteOne struct {
	_d *SystemMetadataDelete
}

// Where appends a list predicates to the SystemMetadataDelete builder.
func (_d *SystemMetadataDeleteOne) Where(ps ...predicate.SystemMetadata) *SystemMetadataDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SystemMetadataDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{systemmetadata.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SystemMetadataDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
