// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/vandordev/vkit-fast/internal/platform/db/predicate"
	"github.com/vandordev/vkit-fast/internal/platform/db/systemmetadata"
)

// SystemMetadataUpdate is the builder for updating SystemMetadata entities.
type SystemMetadataUpdate struct {
	config
	hooks    []Hook
	mutation *SystemMetadataMutation
}

// Where appends a list predicates to the SystemMetadataUpdate builder.
func (_u *SystemMetadataUpdate) Where(ps ...predicate.SystemMetadata) *SystemMetadataUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *SystemMetadataUpdate) SetKey(v string) *SystemMetadataUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *SystemMetadataUpdate) SetNillableKey(v *string) *SystemMetadataUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *SystemMetadataUpdate) SetValue(v map[string]interface{}) *SystemMetadataUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SystemMetadataUpdate) SetUpdatedAt(v time.Time) *SystemMetadataUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SystemMetadataMutation object of the builder.
func (_u *SystemMetadataUpdate) Mutation() *SystemMetadataMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SystemMetadataUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemMetadataUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SystemMetadataUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemMetadataUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SystemMetadataUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := systemmetadata.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SystemMetadataUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := systemmetadata.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`db: validator failed for field "SystemMetadata.key": %w`, err)}
		}
	}
	return nil
}

func (_u *SystemMetadataUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemmetadata.Table, systemmetadata.Columns, sqlgraph.NewFieldSpec(systemmetadata.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(systemmetadata.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(systemmetadata.FieldValue, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(systemmetadata.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemmetadata.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SystemMetadataUpdateOne is the builder for updating a single SystemMetadata entity.
type SystemMetadataUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SystemMetadataMutation
}

// SetKey sets the "key" field.
func (_u *SystemMetadataUpdateOne) SetKey(v string) *SystemMetadataUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *SystemMetadataUpdateOne) SetNillableKey(v *string) *SystemMetadataUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *SystemMetadataUpdateOne) SetValue(v map[string]interface{}) *SystemMetadataUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SystemMetadataUpdateOne) SetUpdatedAt(v time.Time) *SystemMetadataUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SystemMetadataMutation object of the builder.
func (_u *SystemMetadataUpdateOne) Mutation() *SystemMetadataMutation {
	return _u.mutation
}

// Where appends a list predicates to the SystemMetadataUpdate builder.
func (_u *SystemMetadataUpdateOne) Where(ps ...predicate.SystemMetadata) *SystemMetadataUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SystemMetadataUpdateOne) Select(field string, fields ...string) *SystemMetadataUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SystemMetadata entity.
func (_u *SystemMetadataUpdateOne) Save(ctx context.Context) (*SystemMetadata, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemMetadataUpdateOne) SaveX(ctx context.Context) *SystemMetadata {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SystemMetadataUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemMetadataUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SystemMetadataUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := systemmetadata.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SystemMetadataUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := systemmetadata.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`db: validator failed for field "SystemMetadata.key": %w`, err)}
		}
	}
	return nil
}

func (_u *SystemMetadataUpdateOne) sqlSave(ctx context.Context) (_node *SystemMetadata, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemmetadata.Table, systemmetadata.Columns, sqlgraph.NewFieldSpec(systemmetadata.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "SystemMetadata.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, systemmetadata.FieldID)
		for _, f := range fields {
			if !systemmetadata.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != systemmetadata.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(systemmetadata.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(systemmetadata.FieldValue, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(systemmetadata.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SystemMetadata{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemmetadata.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
