FROM golang:1.25-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /migrate ./apps/migrate
FROM alpine:3.22
WORKDIR /app
RUN addgroup --system --gid 1001 app && adduser --system --uid 1001 --ingroup app app
COPY --from=build --chown=app:app /migrate /migrate
COPY --chown=app:app config ./config
COPY --chown=app:app database ./database
USER app
CMD ["/migrate"]
