FROM golang:1.25-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /worker ./apps/worker
FROM alpine:3.22
WORKDIR /app
COPY --from=build /worker /worker
COPY config ./config
CMD ["/worker"]
