package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const banner = "// Code generated by vandor sync. DO NOT EDIT.\n\n"

type surface struct{ name, directory, filename, contract string }
type entry struct{ importPath, pkg, constructor, typeName string }

var surfaces = []surface{
	{"usecase", "internal/usecase", "usecases_gen.go", "contract.Command"},
	{"http", "internal/transport/http/handler", "http_gen.go", "contract.HTTPHandler"},
	{"worker", "internal/worker/river", "worker_gen.go", "contract.WorkerRegistrar"},
	{"scheduler", "internal/scheduler/river", "scheduler_gen.go", "contract.SchedulerRegistrar"},
}

func main() {
	selected := flag.String("surface", "all", "usecase|http|worker|scheduler|all")
	flag.Parse()
	if err := sync(".", *selected); err != nil {
		panic(err)
	}
}

func sync(root, selected string) error {
	if selected != "all" && selected != "usecase" && selected != "http" && selected != "worker" && selected != "scheduler" {
		return fmt.Errorf("unsupported surface %q", selected)
	}
	module, err := modulePath(root)
	if err != nil {
		return err
	}
	for _, item := range surfaces {
		if selected != "all" && selected != item.name {
			continue
		}
		entries, err := discover(root, module, item)
		if err != nil {
			return err
		}
		if err := writeRegistry(root, module, item, entries); err != nil {
			return err
		}
	}
	return nil
}

func modulePath(root string) (string, error) {
	b, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return "", err
	}
	for _, line := range strings.Split(string(b), "\n") {
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module ")), nil
		}
	}
	return "", fmt.Errorf("go.mod has no module path")
}

func discover(root, module string, item surface) ([]entry, error) {
	var entries []entry
	directory := filepath.Join(root, item.directory)
	err := filepath.WalkDir(directory, func(path string, dir os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if dir.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		file, err := parser.ParseFile(token.NewFileSet(), path, nil, 0)
		if err != nil {
			return err
		}
		declared := map[string]bool{}
		for _, decl := range file.Decls {
			if gen, ok := decl.(*ast.GenDecl); ok && gen.Tok == token.TYPE {
				for _, spec := range gen.Specs {
					declared[spec.(*ast.TypeSpec).Name.Name] = true
				}
			}
		}
		hasContract := false
		for _, decl := range file.Decls {
			if gen, ok := decl.(*ast.GenDecl); ok {
				for _, spec := range gen.Specs {
					if strings.Contains(nodeString(spec), item.contract) {
						hasContract = true
					}
				}
			}
		}
		constructors := map[string]bool{}
		for _, decl := range file.Decls {
			if fn, ok := decl.(*ast.FuncDecl); ok && fn.Recv == nil && strings.HasPrefix(fn.Name.Name, "New") {
				constructors[fn.Name.Name] = true
			}
		}
		if hasContract {
			for typeName := range declared {
				if isSurfaceCandidate(item.name, typeName, declared) && !constructors["New"+typeName] {
					return fmt.Errorf("%s: missing New%s constructor", path, typeName)
				}
			}
		}
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Recv != nil || !strings.HasPrefix(fn.Name.Name, "New") {
				continue
			}
			typeName := strings.TrimPrefix(fn.Name.Name, "New")
			if !declared[typeName] || !isSurfaceCandidate(item.name, typeName, declared) {
				continue
			}
			if !hasContract {
				return fmt.Errorf("%s: missing %s assertion", path, item.contract)
			}
			rel, err := filepath.Rel(root, filepath.Dir(path))
			if err != nil {
				return err
			}
			entries = append(entries, entry{importPath: module + "/" + filepath.ToSlash(rel), pkg: file.Name.Name, constructor: fn.Name.Name, typeName: typeName})
		}
		return nil
	})
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].importPath == entries[j].importPath {
			return entries[i].constructor < entries[j].constructor
		}
		return entries[i].importPath < entries[j].importPath
	})
	return entries, err
}

func isSurfaceCandidate(surfaceName, typeName string, declared map[string]bool) bool {
	switch surfaceName {
	case "usecase":
		return declared[typeName+"Input"] && declared[typeName+"Result"]
	case "http":
		return strings.HasSuffix(typeName, "Handler")
	case "worker", "scheduler":
		return strings.HasSuffix(typeName, "Registrar")
	}
	return false
}

func nodeString(node ast.Node) string {
	var b bytes.Buffer
	_ = format.Node(&b, token.NewFileSet(), node)
	return b.String()
}

func writeRegistry(root, module string, item surface, entries []entry) error {
	var b strings.Builder
	b.WriteString(banner)
	b.WriteString("package generatedfx\n\nimport (\n\t\"go.uber.org/fx\"\n")
	if item.name == "usecase" {
		b.WriteString("\t\"" + module + "/internal/contract\"\n")
	}
	if item.name == "worker" || item.name == "scheduler" {
		b.WriteString("\triverqueue \"github.com/riverqueue/river\"\n")
	}
	for _, entry := range entries {
		b.WriteString("\t" + entry.pkg + " \"" + entry.importPath + "\"\n")
	}
	b.WriteString(")\n\nvar " + strings.ToUpper(item.name[:1]) + item.name[1:] + "Module = fx.Options(\n")
	for _, entry := range entries {
		switch item.name {
		case "usecase":
			b.WriteString("\tfx.Provide(fx.Annotate(" + entry.pkg + "." + entry.constructor + ", fx.As(new(contract.Command[" + entry.pkg + "." + entry.typeName + "Input, " + entry.pkg + "." + entry.typeName + "Result])))),\n")
		case "http":
			b.WriteString("\tfx.Provide(" + entry.pkg + "." + entry.constructor + "),\n\tfx.Invoke(func(handler *" + entry.pkg + "." + entry.typeName + ") { handler.RegisterRoutes() }),\n")
		case "worker":
			b.WriteString("\tfx.Provide(" + entry.pkg + "." + entry.constructor + "),\n\tfx.Invoke(func(registrar *" + entry.pkg + "." + entry.typeName + ", workers *riverqueue.Workers) { registrar.RegisterWorkers(workers) }),\n")
		case "scheduler":
			b.WriteString("\tfx.Provide(" + entry.pkg + "." + entry.constructor + "),\n\tfx.Provide(fx.Annotate(func(registrar *" + entry.pkg + "." + entry.typeName + ") []*riverqueue.PeriodicJob { return registrar.RegisterPeriodicJobs() }, fx.ResultTags(`group:\"periodic_jobs,flatten\"`))),\n")
		}
	}
	b.WriteString(")\n")
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return err
	}
	dir := filepath.Join(root, "internal/generated/fx")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, item.filename), formatted, 0o644)
}
