package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const banner = "// Code generated by vandor sync. DO NOT EDIT.\n\n"

type surface struct{ name, directory, filename, contract string }

var surfaces = []surface{
	{"usecase", "internal/usecase", "usecases_gen.go", "contract.Command"},
	{"http", "internal/transport/http/handler", "http_gen.go", "contract.HTTPHandler"},
	{"worker", "internal/worker/river", "worker_gen.go", "contract.WorkerRegistrar"},
	{"scheduler", "internal/scheduler/river", "scheduler_gen.go", "contract.SchedulerRegistrar"},
}

func main() {
	surfaceFlag := flag.String("surface", "all", "usecase|http|worker|scheduler|all")
	flag.Parse()
	if err := sync(".", *surfaceFlag); err != nil {
		panic(err)
	}
}

func sync(root, selected string) error {
	module, err := modulePath(root)
	if err != nil {
		return err
	}
	for _, item := range surfaces {
		if selected != "all" && selected != item.name {
			continue
		}
		if selected != "all" && selected != item.name {
			continue
		}
		constructors, err := discover(filepath.Join(root, item.directory), item.contract)
		if err != nil {
			return err
		}
		if err := writeRegistry(root, module, item, constructors); err != nil {
			return err
		}
	}
	if selected != "all" && selected != "usecase" && selected != "http" && selected != "worker" && selected != "scheduler" {
		return fmt.Errorf("unsupported surface %q", selected)
	}
	return nil
}

func modulePath(root string) (string, error) {
	b, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return "", err
	}
	for _, line := range strings.Split(string(b), "\n") {
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module ")), nil
		}
	}
	return "", fmt.Errorf("go.mod has no module path")
}

func discover(directory, required string) ([]string, error) {
	var constructors []string
	err := filepath.WalkDir(directory, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		file, err := parser.ParseFile(token.NewFileSet(), path, nil, 0)
		if err != nil {
			return err
		}
		var fileConstructors []string
		for _, decl := range file.Decls {
			if fn, ok := decl.(*ast.FuncDecl); ok && fn.Recv == nil && strings.HasPrefix(fn.Name.Name, "New") {
				fileConstructors = append(fileConstructors, fn.Name.Name)
			}
		}
		if len(fileConstructors) == 0 {
			return nil
		}
		hasContract := false
		for _, decl := range file.Decls {
			if value, ok := decl.(*ast.GenDecl); ok {
				for _, spec := range value.Specs {
					if strings.Contains(nodeString(spec), required) {
						hasContract = true
					}
				}
			}
		}
		if !hasContract {
			return nil
		}
		constructors = append(constructors, fileConstructors...)
		return nil
	})
	sort.Strings(constructors)
	return constructors, err
}

func nodeString(node ast.Node) string {
	var b bytes.Buffer
	_ = format.Node(&b, token.NewFileSet(), node)
	return b.String()
}

func writeRegistry(root, module string, item surface, constructors []string) error {
	var b strings.Builder
	b.WriteString(banner)
	b.WriteString("package generatedfx\n\n")
	b.WriteString("import (\n\t\"go.uber.org/fx\"\n")
	if item.name == "usecase" {
		b.WriteString("\t\"" + module + "/internal/contract\"\n")
	}
	if item.name == "http" {
		b.WriteString("\t\"" + module + "/internal/transport/http/handler/system_metadata\"\n")
	} else {
		b.WriteString("\t\"" + module + "/" + item.directory + "\"\n")
	}
	b.WriteString(")\n\n")
	name := strings.ToUpper(item.name[:1]) + item.name[1:] + "Module"
	b.WriteString("var " + name + " = fx.Options(\n")
	for _, constructor := range constructors {
		pkg := filepath.Base(item.directory)
		if item.name == "http" {
			pkg = "system_metadata"
		}
		if item.name == "usecase" {
			b.WriteString("\tfx.Provide(fx.Annotate(" + pkg + "." + constructor + ", fx.As(new(contract.Command[" + pkg + "." + strings.TrimPrefix(constructor, "New") + "Input, " + pkg + "." + strings.TrimPrefix(constructor, "New") + "Result])))),\n")
		} else {
			b.WriteString("\tfx.Provide(" + pkg + "." + constructor + "),\n")
		}
	}
	if item.name == "http" {
		b.WriteString("\tfx.Invoke(func(handler *system_metadata.SetSystemMetadataHandler) { handler.RegisterRoutes() }),\n")
	}
	b.WriteString(")\n")
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return err
	}
	dir := filepath.Join(root, "internal/generated/fx")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, item.filename), formatted, 0o644)
}
