PORT: ${PORT:-4101}
CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:4100}
OPENAPI_SERVER_URL: ${OPENAPI_SERVER_URL:-http://localhost:4101}
OPENAPI_BASIC_AUTH_USERNAME: ${OPENAPI_BASIC_AUTH_USERNAME:-}
OPENAPI_BASIC_AUTH_PASSWORD: ${OPENAPI_BASIC_AUTH_PASSWORD:-}
