// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// SystemMetadata is the predicate function for systemmetadata builders.
type SystemMetadata func(*sql.Selector)
